on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
      - uses: actions/checkout@v2

      - name: run the action
        id: hello
        uses: ./
        with:
          myInput: 'James T'

      - name: output
        run: |
          echo ${{ steps.hello.outputs.memory }}
          echo "total memory output"
